baseURL = 'https://intellux.ai/'
languageCode = 'en-us'
title = 'InCheck'
enableRobotsTXT = true

[taxonomies]
  tag = ""
  category = ""

ignoreFiles = ["\\.DS_Store$", "public/.*", "hugo_build.lock"]