baseURL = 'https://intellux.ai/'
languageCode = 'en-us'
title = 'InCheck'

[outputFormats]
[outputFormats.RobotsTXT]
  mediaType = "text/plain"
  baseName = "robots"
  isPlainText = true

[outputs]
  home = ["HTML", "RSS", "RobotsTXT"]

[taxonomies]
  tag = ""
  category = ""