cd "C:\Users\MelindaWeathers\Documents\GitHub\incheckupdate1017\InCheckUPDATE"

@'
name = "incheckupdate"

[build]
command = "hugo --minify"
cwd = "InCheckSite"

[vars]
HUGO_VERSION = "0.134.3"

pages_build_output_dir = "InCheckSite/public"
'@ | Set-Content .\wrangler.toml -Encoding UTF8

git add .\wrangler.toml
git commit -m "build: pin Cloudflare Pages config via wrangler.toml"
git push
