# Deploys Hugo site to Cloudflare Pages on pushes to main
#
# Prerequisites (Repository settings):
# - Secrets:
#   - CLOUDFLARE_API_TOKEN: API token with Pages - Edit permission
#   - CLOUDFLARE_ACCOUNT_ID: Your Cloudflare account ID
# - Variables:
#   - CLOUDFLARE_PAGES_PROJECT: Cloudflare Pages project name (non-secret)

name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: cloudflare-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT }}
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
